### PR TITLE
Apply spotless fixes

### PR DESCRIPTION
**Pull request by hagafrank**
We need to make use of spotless checks so that we have some level of consistency when it comes to white spaces and remove things like unused imports and unused private methods; basically, clean up the code with the tools available.

I suggest we add the spotless check each time someone submits a PR.

`./gradlew :fineract-provider:spotlessCheck`

The issues raised by this command can be addressed by running this `./gradlew :fineract-provider:spotlessApply`

This is a practice in the community that we should adopt.

### CODE REVIEW

**Comment by hagafrank** [comment]
@Napho @hiteshprajapati kindly assist with this

**Review by hiteshprajapati — APPROVED** [review]

**Comment by Napho** [comment]
@hagafrank conflict here, also maybe we can add a sanity checks workflow in this repo so atleast we dont merge anything with spotless checks failing

**Comment by hagafrank** [comment]
Yes, that's the idea.... there are conflicts here because the PR has been in the queue for a while. I can close it and submit a new one. That will been to be merged ASAP. But yes, I agree with the idea of the sanity checks

**Comment by hagafrank** [comment]
will issue a new PR

**Pull request closed without merging**
