### PR TITLE
CI18-117 - Fixing migration script

### PR DESCRIPTION
**Pull request by jumba2010**
## Description

Describe the changes made and why they were made.

Ignore if these details are present on the associated [Apache Fineract JIRA ticket](https://github.com/apache/fineract/pull/1284).

## Checklist

Please make sure these boxes are checked before submitting your pull request - thanks!

- [ ] Write the commit message as per https://github.com/apache/fineract/#pull-requests

- [ ] Acknowledge that we will not review PRs that are not passing the build _("green")_ - it is your responsibility to get a proposed PR to pass the build, not primarily the project's maintainers.

- [ ] Create/update unit or integration tests for verifying the changes made.

- [ ] Follow coding conventions at https://cwiki.apache.org/confluence/display/FINERACT/Coding+Conventions.

- [ ] Add required Swagger annotation and update API documentation at fineract-provider/src/main/resources/static/legacy-docs/apiLive.htm with details of any API changes

- [ ] Submission is not a "code dump".  (Large changes can be made "in repository" via a branch.  Ask on the developer mailing list for guidance, if required.)

FYI our guidelines for code reviews are at https://cwiki.apache.org/confluence/display/FINERACT/Code+Review+Guide.

### CODE REVIEW

**Review by BrianMuhimbura — APPROVED** [review]

**Review by hagafrank — CHANGES_REQUESTED** [review]
Is this not going to cause md5 checksum mismatch errors? Why are we changing a migrations script that has already been run?

**Comment by jumba2010** [comment]
> Is this not going to cause md5 checksum mismatch errors? Why are we changing a migrations script that has already been run?
There was an extra unnecessary insert statement. It will not give any error because I have changed the migration id.

**Comment by hagafrank** [comment]
So will it attempt to run again. Please test to be sure

**Comment by jumba2010** [comment]
> So will it attempt to run again. Please test to be sure

Yeah. It will try to run it again, but because there is a precondition check at the beginning witch verifies if the table m_loan_redraw_account is already there, it will not execute. I have run it on my local, and it does not give any error.

**Review by hagafrank — APPROVED** [review]
ok, fair enough

**Pull request merged**
